[connections.snowflake]
account = "AZYEQSP-VFB81562"
user = "timnussbaum"
password = "mhmKar000!snowflake"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
